milvus:
  host: 127.0.0.1
  port: 19530
  collection_name: tender_vector_collection
  vector_dim:
  top_k: 10

minio:
  # .env
  host: localhost:9010
  access_key: minioadmin
  secret_key: minioadmin
  bucket_name: tender